CREATE TABLE user_profile_picture (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	date_created TIMESTAMPTZ DEFAULT now() NOT NULL,
	img_type TEXT NOT NULL,
	img_file bytea NOT NULL,
    user_id INTEGER
        REFERENCES user_information(id) ON DELETE CASCADE NOT NULL
);