CREATE TABLE post_caption (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    caption TEXT NOT NULL,
    date_created TIMESTAMPTZ DEFAULT now() NOT NULL,
    date_modified TIMESTAMPTZ,
    post_photo_id INTEGER
        REFERENCES post_photo(id) ON DELETE CASCADE NOT NULL,
    user_id INTEGER
        REFERENCES user_information(id) ON DELETE CASCADE NOT NULL
);